import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="pt-BR"
      className="h-full bg-gray-600  text-zinc-900  font-sans"
    >
      <body className="min-h-full flex flex-col bg-gray-800">{children}</body>
    </html>
  );
}
